
project_id = "ztwntsmwzstvmoqgiztc"

[functions.create-business]
verify_jwt = false

[functions.complete-business-setup]
verify_jwt = false

[functions.check-slug-availability]
verify_jwt = false

[functions.check-business-status]
verify_jwt = false

[functions.efipay-payment-handler]
verify_jwt = false
