
project_id = "jcdymkgmtxpryceziazt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

# Allow public access to the webhook endpoint without authentication
[functions.efipay-webhook]
verify_jwt = false

# Allow creating businesses with admin privileges
[functions.create-business]
verify_jwt = true
timeout_ms = 60000

# Allow checking slug availability
[functions.check-slug-availability]
verify_jwt = true

# Function to complete business setup after initial creation
[functions.complete-business-setup]
verify_jwt = true
timeout_ms = 30000
