
project_id = "ztwntsmwzstvmoqgiztc"

[functions.create-business]
verify_jwt = false

[functions.complete-business-setup]
verify_jwt = false

[functions.check-business-status]
verify_jwt = false

[functions.check-slug-availability]
verify_jwt = false

# Adicionar política para executar RPC functions
[auth.policies.rpc.execute.verificar_completar_onboarding]
type = "after_auth"
roles = ["authenticated"]

[auth.policies.rpc.execute.obter_metricas_periodo]
type = "after_auth"  
roles = ["authenticated"]
