
import { Professional, ProfessionalStatus } from "./types";

export const mockProfessionals: Professional[] = [
  {
    id: "1",
    name: "John Doe",
    role: "Barber",
    email: "john.doe@example.com",
    phone: "555-1234",
    specialties: ["Haircut", "Beard Trim"],
    photoUrl: "https://randomuser.me/api/portraits/men/1.jpg",
    bio: "Expert barber with 5 years of experience",
    status: ProfessionalStatus.ACTIVE,
    hireDate: "2022-01-15",
    commissionPercentage: 25,
    userId: "user1",
    business_id: "business1"
  },
  {
    id: "2",
    name: "Jane Smith",
    role: "Stylist",
    email: "jane.smith@example.com",
    phone: "555-5678",
    specialties: ["Coloring", "Highlights", "Styling"],
    photoUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    bio: "Creative stylist specializing in color transformations",
    status: ProfessionalStatus.ACTIVE,
    hireDate: "2021-08-10",
    commissionPercentage: 30,
    userId: "user2",
    business_id: "business1"
  },
  {
    id: "3",
    name: "Mike Johnson",
    role: "Barber",
    email: "mike.johnson@example.com",
    phone: "555-9876",
    specialties: ["Haircut", "Shaving"],
    photoUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    bio: "Traditional barber with attention to detail",
    status: ProfessionalStatus.INACTIVE,
    hireDate: "2020-05-20",
    commissionPercentage: 25,
    userId: "user3",
    business_id: "business1"
  },
  {
    id: "4",
    name: "Emily Davis",
    role: "Manicurist",
    email: "emily.davis@example.com",
    phone: "555-4321",
    specialties: ["Manicure", "Pedicure", "Nail Art"],
    photoUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    bio: "Nail artist with a passion for creative designs",
    status: ProfessionalStatus.ACTIVE,
    hireDate: "2022-03-15",
    commissionPercentage: 25,
    userId: "user4",
    business_id: "business1"
  },
  {
    id: "5",
    name: "Robert Wilson",
    role: "Hair Stylist",
    email: "robert.wilson@example.com",
    phone: "555-8765",
    specialties: ["Haircut", "Styling", "Extensions"],
    photoUrl: "https://randomuser.me/api/portraits/men/3.jpg",
    bio: "Experienced stylist specialized in modern techniques",
    status: ProfessionalStatus.ON_LEAVE,
    hireDate: "2021-11-05",
    commissionPercentage: 30,
    userId: "user5",
    business_id: "business1"
  },
  {
    id: "6",
    name: "Sarah Thompson",
    role: "Esthetician",
    email: "sarah.thompson@example.com",
    phone: "555-2345",
    specialties: ["Facials", "Waxing", "Skincare"],
    photoUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    bio: "Licensed esthetician offering premium skincare services",
    status: ProfessionalStatus.ACTIVE,
    hireDate: "2022-01-25",
    commissionPercentage: 28,
    userId: "user6",
    business_id: "business1"
  }
];
